version: "3.0"

services:
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: articles
      POSTGRES_PASSWORD: ET@117
      POSTGRES_HOST: localhost

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - db
      
volumes:
  postgresql-data: